import React from "react";

export const routes = [
  {
    to: null,
    title: "Creación de componentes",
    description: "",
    component: React.lazy(() => import("../pages/Home")),
  },
  {
    to: "Ejem1",
    title: "Componente usando clases",
    description: "Muestra como crear un componente usando clases. Obsoleto.",
    component: React.lazy(() => import("../pages/Ejem01")),
  },
  {
    to: "Ejem2",
    title: "Componentes dentro de componentes",
    description: "Uso de componentes anidados.",
    component: React.lazy(() => import("../pages/Ejem02")),
  },
  {
    to: "Ejem3",
    title: "Componentes condicionales",
    description: "Uso del if.",
    component: React.lazy(() => import("../pages/Ejem03")),
  },
  {
    to: "Ejem4",
    title: "Props",
    description: "Paso de props al componente.",
    component: React.lazy(() => import("../pages/Ejem04")),
  },
  {
    to: "Ejem5",
    title: "Estilos en react",
    description: "Como poner estilos en react.",
    component: React.lazy(() => import("../pages/Ejem05")),
  },
  {
    to: "Ejem6",
    title: "Pasar funciones de padre a hijo",
    description: "Usar Props y pasar funciones.",
    component: React.lazy(() => import("../pages/Ejem06")),
  },
  {
    to: "Ejem7",
    title: "Hook useState",
    description: "Como usar variables que varian **IMPORTANTE**.",
    component: React.lazy(() => import("../pages/Ejem07")),
  },
  {
    to: "Ejem8",
    title: "Como pasar children",
    description: "Como pasar children de un componente ademas de tipar como React.ReactNode.",
    component: React.lazy(() => import("../pages/Ejem08")),
  },
  {
    to: "Ejem9",
    title: "Null",
    description: "Null.",
    component: React.lazy(() => import("../pages/Ejem09")),
  },
  {
    to: "Ejem10",
    title: "Null",
    description: "Null.",
    component: React.lazy(() => import("../pages/Ejem10")),
  },
  {
    to: "Ejem11",
    title: "Null",
    description: "Null.",
    component: React.lazy(() => import("../pages/Ejem11")),
  },
  {
    to: "Ejem12",
    title: "Null",
    description: "Null.",
    component: React.lazy(() => import("../pages/Ejem12")),
  },
  {
    to: "Ejem13",
    title: "Null",
    description: "Null.",
    component: React.lazy(() => import("../pages/Ejem13")),
  },
  {
    to: "Ejem14",
    title: "Null",
    description: "Null.",
    component: React.lazy(() => import("../pages/Ejem14")),
  },
  {
    to: "Ejem15",
    title: "Null",
    description: "Null.",
    component: React.lazy(() => import("../pages/Ejem15")),
  },
  {
    to: "Ejem16",
    title: "Null",
    description: "Null.",
    component: React.lazy(() => import("../pages/Ejem16")),
  },
  {
    to: "Ejem17",
    title: "Null",
    description: "Null.",
    component: React.lazy(() => import("../pages/Ejem17")),
  },
  {
    to: "Ejem18",
    title: "Null",
    description: "Null.",
    component: React.lazy(() => import("../pages/Ejem18")),
  },
  {
    to: "Ejem19",
    title: "Null",
    description: "Null.",
    component: React.lazy(() => import("../pages/Ejem19")),
  },
  {
    to: "Ejem20",
    title: "Null",
    description: "Null.",
    component: React.lazy(() => import("../pages/Ejem20")),
  },
  {
    to: "Ejem21",
    title: "Null",
    description: "Null.",
    component: React.lazy(() => import("../pages/Ejem21")),
  },
  {
    to: "Ejem22",
    title: "Null",
    description: "Null.",
    component: React.lazy(() => import("../pages/Ejem22")),
  },
  {
    to: "Ejem23",
    title: "Null",
    description: "Null.",
    component: React.lazy(() => import("../pages/Ejem23")),
  },
  {
    to: "Ejem24",
    title: "Null",
    description: "Null.",
    component: React.lazy(() => import("../pages/Ejem24")),
  },
  {
    to: "Ejer01",
    title: "Null",
    description: "Null.",
    component: React.lazy(() => import("../pages/Ejer01")),
  },
  {
    to: "Ejer02",
    title: "Null",
    description: "Null.",
    component: React.lazy(() => import("../pages/Ejer02")),
  },
  {
    to: "Ejer03",
    title: "Null",
    description: "Null.",
    component: React.lazy(() => import("../pages/Ejer03")),
  },
  {
    to: "Ejer04",
    title: "Null",
    description: "Null.",
    component: React.lazy(() => import("../pages/Ejer04")),
  },
  {
    to: "Ejer05",
    title: "Null",
    description: "Null.",
    component: React.lazy(() => import("../pages/Ejer05")),
  },
  {
    to: "Ejer06",
    title: "Null",
    description: "Null.",
    component: React.lazy(() => import("../pages/Ejer06")),
  },
  {
    to: "Ejer07",
    title: "Null",
    description: "Null.",
    component: React.lazy(() => import("../pages/Ejer07")),
  },
  {
    to: "Ejer08",
    title: "Null",
    description: "Null.",
    component: React.lazy(() => import("../pages/Ejer08")),
  },
  {
    to: "Ejer09",
    title: "Null",
    description: "Null.",
    component: React.lazy(() => import("../pages/Ejer09")),
  },
  {
    to: "Ejer10",
    title: "Null",
    description: "Null.",
    component: React.lazy(() => import("../pages/Ejer10")),
  }
];